export const usersData = [
    {
        UserID: "user123",
        Username: "John Doe",
        Email: "johndoe@example.com",
        Password: "password123",
        UserType: "Intern",
        ProfileCreatedDate: "2022-01-01",
        InternProfile: {
            ProfileID: "profile123",
            UserID: "user123",
            Name: "John Doe",
            Age: 22,
            Skills: ["JavaScript", "React"],
        },
    },
    {
        UserID: "user456",
        Username: "Jane Smith",
        Email: "janesmith@example.com",
        Password: "password456",
        UserType: "Company",
        CompanyID: "comp456", // Added CompanyID
        ProfileCreatedDate: "2022-01-02",
    },
    {
        UserID: "user789",
        Username: "Bob Johnson",
        Email: "bobjohnson@example.com",
        Password: "password789",
        UserType: "Company",
        CompanyID: "comp789", // Different CompanyID
        ProfileCreatedDate: "2022-01-03",
    },
];

export const company = {
    id: "comp456",
    name: "Google",
    description:
        "Google LLC is an American multinational technology company that specializes in Internet-related services and products.",
    size: 100000,
    location: "California, United States",
    contactInfo: {
        phone: "+1-650-253-0000",
        email: "contact@google.com",
    },
    departments: [
        {
            name: "Department 1",
            description: "This is department 1",
        },
        {
            name: "Department 2",
            description: "This is department 2",
        },
        {
            name: "Department 3",
            description: "This is department 3",
        },
        {
            name: "Department 4",
            description: "This is department 4",
        },
    ],
};

export const applications = [
    {
        submissionDate: "2022-01-01",
        status: "Pending",
        name: "John Doe",
        position: "Software Developer",
        department: "Engineering",
    },
    {
        submissionDate: "2022-01-02",
        status: "Accepted",
        name: "Jane Doe",
        position: "Data Analyst",
        department: "Data Science",
    },
    {
        submissionDate: "2022-01-03",
        status: "Rejected",
        name: "Jim Doe",
        position: "Product Manager",
        department: "Product",
    },
    {
        submissionDate: "2022-01-03",
        status: "Accepted",
        name: "Ken Doe",
        position: "UI/UX Designer",
        department: "Design",
    },
    // Delete
    {
        submissionDate: "2022-01-01",
        status: "Pending",
        name: "John Doe",
        position: "Software Developer",
        department: "Engineering",
    },
    {
        submissionDate: "2022-01-02",
        status: "Accepted",
        name: "Jane Doe",
        position: "Data Analyst",
        department: "Data Science",
    },
    {
        submissionDate: "2022-01-03",
        status: "Rejected",
        name: "Jim Doe",
        position: "Product Manager",
        department: "Product",
    },
    {
        submissionDate: "2022-01-03",
        status: "Accepted",
        name: "Ken Doe",
        position: "UI/UX Designer",
        department: "Design",
    },
    {
        submissionDate: "2022-01-01",
        status: "Pending",
        name: "John Doe",
        position: "Software Developer",
        department: "Engineering",
    },
    {
        submissionDate: "2022-01-02",
        status: "Accepted",
        name: "Jane Doe",
        position: "Data Analyst",
        department: "Data Science",
    },
    {
        submissionDate: "2022-01-03",
        status: "Rejected",
        name: "Jim Doe",
        position: "Product Manager",
        department: "Product",
    },
    {
        submissionDate: "2022-01-03",
        status: "Accepted",
        name: "Ken Doe",
        position: "UI/UX Designer",
        department: "Design",
    },
    {
        submissionDate: "2022-01-01",
        status: "Pending",
        name: "John Doe",
        position: "Software Developer",
        department: "Engineering",
    },
    {
        submissionDate: "2022-01-02",
        status: "Accepted",
        name: "Jane Doe",
        position: "Data Analyst",
        department: "Data Science",
    },
    {
        submissionDate: "2022-01-03",
        status: "Rejected",
        name: "Jim Doe",
        position: "Product Manager",
        department: "Product",
    },
    {
        submissionDate: "2022-01-03",
        status: "Accepted",
        name: "Ken Doe",
        position: "UI/UX Designer",
        department: "Design",
    },
];

export const jobListings = [
    {
        title: "Software Developer",
        description: "Develop and maintain software applications",
        requirements: "Knowledge in JavaScript, React, and Node.js",
        duration: "Full Time",
        deadline: "2022-12-31",
        department: "Engineering",
    },
    {
        title: "Data Analyst",
        description: "Analyze and interpret complex data sets",
        requirements: "Knowledge in SQL, Python, and data visualization tools",
        duration: "Part Time",
        deadline: "2022-11-30",
        department: "Data Science",
    },
    {
        title: "Product Manager",
        description: "Manage product development and strategy",
        requirements: "Experience in product management and business strategy",
        duration: "Contract",
        deadline: "2022-10-31",
        department: "Product",
    },
    {
        title: "UI/UX Designer",
        description: "Design user interfaces and user experiences",
        requirements: "Knowledge in design tools like Sketch and Figma",
        duration: "Full Time",
        deadline: "2022-09-30",
        department: "Design",
    },

    // Delete
    {
        title: "Software Developer",
        description: "Develop and maintain software applications",
        requirements: "Knowledge in JavaScript, React, and Node.js",
        duration: "Full Time",
        deadline: "2022-12-31",
        department: "Engineering",
    },
    {
        title: "Data Analyst",
        description: "Analyze and interpret complex data sets",
        requirements: "Knowledge in SQL, Python, and data visualization tools",
        duration: "Part Time",
        deadline: "2022-11-30",
        department: "Data Science",
    },
    {
        title: "Product Manager",
        description: "Manage product development and strategy",
        requirements: "Experience in product management and business strategy",
        duration: "Contract",
        deadline: "2022-10-31",
        department: "Product",
    },
    {
        title: "UI/UX Designer",
        description: "Design user interfaces and user experiences",
        requirements: "Knowledge in design tools like Sketch and Figma",
        duration: "Full Time",
        deadline: "2022-09-30",
        department: "Design",
    },
    {
        title: "Software Developer",
        description: "Develop and maintain software applications",
        requirements: "Knowledge in JavaScript, React, and Node.js",
        duration: "Full Time",
        deadline: "2022-12-31",
        department: "Engineering",
    },
    {
        title: "Data Analyst",
        description: "Analyze and interpret complex data sets",
        requirements: "Knowledge in SQL, Python, and data visualization tools",
        duration: "Part Time",
        deadline: "2022-11-30",
        department: "Data Science",
    },
    {
        title: "Product Manager",
        description: "Manage product development and strategy",
        requirements: "Experience in product management and business strategy",
        duration: "Contract",
        deadline: "2022-10-31",
        department: "Product",
    },
    {
        title: "UI/UX Designer",
        description: "Design user interfaces and user experiences",
        requirements: "Knowledge in design tools like Sketch and Figma",
        duration: "Full Time",
        deadline: "2022-09-30",
        department: "Design",
    },
    {
        title: "Software Developer",
        description: "Develop and maintain software applications",
        requirements: "Knowledge in JavaScript, React, and Node.js",
        duration: "Full Time",
        deadline: "2022-12-31",
        department: "Engineering",
    },
    {
        title: "Data Analyst",
        description: "Analyze and interpret complex data sets",
        requirements: "Knowledge in SQL, Python, and data visualization tools",
        duration: "Part Time",
        deadline: "2022-11-30",
        department: "Data Science",
    },
    {
        title: "Product Manager",
        description: "Manage product development and strategy",
        requirements: "Experience in product management and business strategy",
        duration: "Contract",
        deadline: "2022-10-31",
        department: "Product",
    },
    {
        title: "UI/UX Designer",
        description: "Design user interfaces and user experiences",
        requirements: "Knowledge in design tools like Sketch and Figma",
        duration: "Full Time",
        deadline: "2022-09-30",
        department: "Design",
    },
];
